sudo: required
services:
  - docker
language: node_js
node_js:
  - 'node'
env:
  - ISOLATED=false
addons:
  browserstack:
    username: $BROWSERSTACK_USERNAME
    access_key: $BROWSERSTACK_ACCESS_KEY
    forcelocal: true
branches:
  only:
    - master
    - develop
before_script: 
  - ./start.sh
script:
  - ./test.sh
after_success:
  - ./deploy.sh
