sudo: required
services:
  - docker
language: node_js
node_js:
  - 'node'
  - '8.7.0'
env:
  - ISOLATED=false
branches:
  only:
    - master
    - develop
before_script:
  - ./start.sh
script:
  - ./test.sh
after_success:
  - ./deploy.sh
