sudo: required
services:
  - docker
language: node_js
node_js:
  - '7'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
branches:
  only:
    - master
    - develop
before_script: 
  - ./start.sh
script:
  - ./test.sh
after_success:
  - ./deploy.sh
