export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';

export const SET_LOCALE_START = 'SET_LOCALE_START';
export const SET_LOCALE_SUCCESS = 'SET_LOCALE_SUCCESS';
export const SET_LOCALE_ERROR = 'SET_LOCALE_ERROR';

export const AUTOCOMPLETE_PLACES_START = 'AUTOCOMPLETE_PLACES_START';
export const AUTOCOMPLETE_PLACES_SUCCESS = 'AUTOCOMPLETE_PLACES_SUCCESS';
export const AUTOCOMPLETE_PLACES_ERROR = 'AUTOCOMPLETE_PLACES_ERROR';

export const SELECTED_LOCALITY = 'SELECTED_LOCALITY';

export const SET_PROPERTY = 'SET_PROPERTY';
export const SET_TRANSPORT = 'SET_TRANSPORT';
export const SAVE_LINK_START = 'SAVE_LINK_START';
export const SAVE_LINK_SUCCESS = 'SAVE_LINK_SUCCESS';
export const SAVE_LINK_ERROR = 'SAVE_LINK_ERROR';
export const LINK_RESET = 'LINK_RESET';

export const SEARCH_LINKS_START = 'SEARCH_LINKS_START';
export const SEARCH_LINKS_SUCCESS = 'SEARCH_LINKS_SUCCESS';
export const SEARCH_LINKS_ERROR = 'SEARCH_LINKS_ERROR';

export const SET_LOGIN_PARAMS = 'SET_LOGIN_PARAMS';
export const SET_AUTH = 'SET_AUTH';

export const RESET_PASSWORD_START = 'RESET_PASSWORD_START';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';
export const SAVE_PROFILE_START = 'SAVE_PROFILE_START';
export const SAVE_PROFILE_SUCCESS = 'SAVE_PROFILE_SUCCESS';
export const SAVE_PROFILE_ERROR = 'SAVE_PROFILE_ERROR';
