export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';
export const SET_VAR = 'SET_VAR';

export const SET_LOCALE_START = 'SET_LOCALE_START';
export const SET_LOCALE_SUCCESS = 'SET_LOCALE_SUCCESS';
export const SET_LOCALE_ERROR = 'SET_LOCALE_ERROR';

export const AUTOCOMPLETE_PLACES_START = 'AUTOCOMPLETE_PLACES_START';
export const AUTOCOMPLETE_PLACES_SUCCESS = 'AUTOCOMPLETE_PLACES_SUCCESS';
export const AUTOCOMPLETE_PLACES_ERROR = 'AUTOCOMPLETE_PLACES_ERROR';

export const SELECTED_LOCALITY = 'SELECTED_LOCALITY';
export const SELECTED_ADDRESS = 'SELECTED_ADDRESS';

export const SET_PROPERTY = 'SET_PROPERTY';
export const SET_TRANSPORT = 'SET_TRANSPORT';
export const SAVE_LINK_START = 'SAVE_LINK_START';
export const SAVE_LINK_SUCCESS = 'SAVE_LINK_SUCCESS';
export const SAVE_LINK_ERROR = 'SAVE_LINK_ERROR';
export const DELETE_LINK_START = 'DELETE_LINK_START';
export const DELETE_LINK_SUCCESS = 'DELETE_LINK_SUCCESS';
export const DELETE_LINK_ERROR = 'DELETE_LINK_ERROR';
export const LINK_RESET = 'LINK_RESET';

export const SEARCH_LINKS_START = 'SEARCH_LINKS_START';
export const SEARCH_LINKS_SUCCESS = 'SEARCH_LINKS_SUCCESS';
export const SEARCH_LINKS_ERROR = 'SEARCH_LINKS_ERROR';

export const SEARCH_MEDIA_START = 'SEARCH_MEDIA_START';
export const SEARCH_MEDIA_SUCCESS = 'SEARCH_MEDIA_SUCCESS';
export const SEARCH_MEDIA_ERROR = 'SEARCH_MEDIA_ERROR';

export const SET_LOGIN_PARAMS = 'SET_LOGIN_PARAMS';
export const SET_AUTH = 'SET_AUTH';

export const RESET_PASSWORD_START = 'RESET_PASSWORD_START';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';
export const SAVE_PROFILE_START = 'SAVE_PROFILE_START';
export const SAVE_PROFILE_SUCCESS = 'SAVE_PROFILE_SUCCESS';
export const SAVE_PROFILE_ERROR = 'SAVE_PROFILE_ERROR';

export const SAVE_RATING_START = 'SAVE_RATING_START';
export const SAVE_RATING_SUCCESS = 'SAVE_RATING_SUCCESS';
export const SAVE_RATING_ERROR = 'SAVE_RATING_ERROR';

export const SAVE_COMMENT_START = 'SAVE_COMMENT_START';
export const SAVE_COMMENT_SUCCESS = 'SAVE_COMMENT_SUCCESS';
export const SAVE_COMMENT_ERROR = 'SAVE_COMMENT_ERROR';

export const GET_COMMENTS_START = 'GET_COMMENTS_START';
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const GET_COMMENTS_ERROR = 'GET_COMMENTS_ERROR';

export const VOTE_START = 'VOTE_START';
export const VOTE_SUCCESS = 'VOTE_SUCCESS';
export const VOTE_ERROR = 'VOTE_ERROR';

export const INSTANCE_FILE_UPLOAD_START = 'INSTANCE_FILE_UPLOAD_START';
export const INSTANCE_FILE_UPLOAD_SUCCESS = 'INSTANCE_FILE_UPLOAD_SUCCESS';
export const INSTANCE_FILE_UPLOAD_ERROR = 'INSTANCE_FILE_UPLOAD_ERROR';

