export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';

export const SET_LOCALE_START = 'SET_LOCALE_START';
export const SET_LOCALE_SUCCESS = 'SET_LOCALE_SUCCESS';
export const SET_LOCALE_ERROR = 'SET_LOCALE_ERROR';

export const AUTOCOMPLETE_PLACES_START = 'AUTOCOMPLETE_PLACES_START';
export const AUTOCOMPLETE_PLACES_SUCCESS = 'AUTOCOMPLETE_PLACES_SUCCESS';
export const AUTOCOMPLETE_PLACES_ERROR = 'AUTOCOMPLETE_PLACES_ERROR';

export const SELECTED_LOCALITY = 'SELECTED_LOCALITY';

export const SAVE_LINK_START = 'SAVE_LINK_START';
export const SAVE_LINK_SUCCESS = 'SAVE_LINK_SUCCESS';
export const SAVE_LINK_ERROR = 'SAVE_LINK_ERROR';

export const LINK_RESET = 'LINK_RESET';
